import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import MyNavbar from "@components/componentsHomePage/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={{backgroundColor: '#f4e1d1'}}>
        <MyNavbar />
        {children}
      </body>
    </html>
  );
}
